import Link from "next/link";
import { motion } from "framer-motion";

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950 to-slate-900 text-white">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 bg-black/30 backdrop-blur-lg border-b border-white/10">
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 group">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500 to-purple-500 flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform">
                C
              </div>
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
                Caapify
              </span>
            </Link>

            <div className="flex items-center gap-6">
              <Link href="/" className="text-white/80 hover:text-white transition-colors font-medium">
                Home
              </Link>
              <Link href="/about" className="text-white/80 hover:text-white transition-colors font-medium">
                About
              </Link>
              <Link href="/privacy" className="text-white/80 hover:text-white transition-colors font-medium">
                Privacy
              </Link>
              <Link href="/contact" className="text-white/80 hover:text-white transition-colors font-medium">
                Contact
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="relative rounded-2xl p-1 bg-gradient-to-r from-cyan-500/30 to-purple-500/30"
        >
          <div className="bg-slate-900/90 backdrop-blur-xl rounded-2xl p-8 md:p-12 border border-white/10">
            <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
              Terms of Service
            </h1>
            <p className="text-white/60 mb-8">Last updated: January 2026</p>

            <div className="space-y-6 text-white/80 leading-relaxed">
              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">1. Acceptance of Terms</h2>
                <p>
                  By accessing and using Caapify, you accept and agree to be bound by the terms 
                  and provision of this agreement. If you do not agree to these terms, please 
                  do not use our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">2. Description of Service</h2>
                <p>
                  Caapify provides an AI-powered tool that analyzes uploaded images to generate 
                  social media captions, song recommendations, and hashtags. The service is 
                  provided "as is" and we reserve the right to modify or discontinue the service 
                  at any time.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">3. User Responsibilities</h2>
                <p className="mb-3">When using Caapify, you agree to:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Provide accurate and complete information</li>
                  <li>Use the service only for lawful purposes</li>
                  <li>Not upload images that contain illegal, harmful, or offensive content</li>
                  <li>Not attempt to interfere with or disrupt the service</li>
                  <li>Not use the service to violate anyone's intellectual property rights</li>
                  <li>Respect the privacy and rights of others</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">4. Content Ownership</h2>
                <p>
                  You retain all rights to the images you upload. By using our service, you 
                  grant Caapify a temporary, non-exclusive license to process your images for 
                  the sole purpose of providing our AI generation service. We do not claim 
                  ownership of your content.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">5. AI-Generated Content</h2>
                <p>
                  The captions, songs, and hashtags generated by our AI are suggestions only. 
                  While we strive for accuracy and relevance, we cannot guarantee that all 
                  AI-generated content will be appropriate for your specific use case. You are 
                  responsible for reviewing and editing content before publishing it.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">6. Prohibited Content</h2>
                <p className="mb-3">You may not upload images that contain:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Illegal activities or content</li>
                  <li>Explicit sexual or violent content</li>
                  <li>Hate speech, harassment, or discriminatory content</li>
                  <li>Content that infringes on intellectual property rights</li>
                  <li>Malware, viruses, or harmful code</li>
                  <li>Personal information of others without consent</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">7. Intellectual Property</h2>
                <p>
                  All content on Caapify, including but not limited to text, graphics, logos, 
                  and software, is the property of Caapify or its licensors and is protected 
                  by copyright and other intellectual property laws.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">8. Limitation of Liability</h2>
                <p>
                  Caapify shall not be liable for any indirect, incidental, special, consequential, 
                  or punitive damages resulting from your use or inability to use the service. 
                  We make no warranties about the accuracy, reliability, or availability of the 
                  service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">9. Service Availability</h2>
                <p>
                  We strive to maintain high availability but do not guarantee that the service 
                  will be uninterrupted, timely, secure, or error-free. We may suspend or 
                  terminate the service for maintenance, updates, or other reasons.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">10. Privacy</h2>
                <p>
                  Your use of Capify is also governed by our Privacy Policy. Please review our{" "}
                  <Link href="/privacy" className="text-cyan-400 hover:text-cyan-300 underline">
                    Privacy Policy
                  </Link>{" "}
                  to understand our practices.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">11. Termination</h2>
                <p>
                  We reserve the right to terminate or suspend access to our service immediately, 
                  without prior notice or liability, for any reason, including if you breach 
                  these Terms of Service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">12. Changes to Terms</h2>
                <p>
                  We reserve the right to modify these terms at any time. Changes will be 
                  effective immediately upon posting. Your continued use of the service after 
                  any changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">13. Governing Law</h2>
                <p>
                  These Terms shall be governed by and construed in accordance with applicable 
                  laws, without regard to its conflict of law provisions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3 text-white">14. Contact Information</h2>
                <p>
                  If you have any questions about these Terms, please contact us:
                </p>
                <div className="mt-4 p-4 bg-white/5 rounded-xl border border-white/10">
                  <p>Email: legal@caapify.com</p>
                  <p className="mt-2">
                    Or visit our{" "}
                    <Link href="/contact" className="text-cyan-400 hover:text-cyan-300 underline">
                      Contact Page
                    </Link>
                  </p>
                </div>
              </section>

              <div className="mt-8 p-6 bg-gradient-to-r from-purple-500/10 to-cyan-500/10 rounded-xl border border-purple-500/20">
                <p className="text-sm text-white/70 text-center">
                  By using Caapify, you acknowledge that you have read, understood, and agree 
                  to be bound by these Terms of Service.
                </p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/10 mt-16 bg-black/20 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-4 py-8">
          <div className="text-center">
            <p className="text-white/40 text-sm">
              © 2026 Caapify. All rights reserved. | Made with AI ✨
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
